name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: ./node_modules/.bin/lerna -v
      - run: ./node_modules/.bin/lerna bootstrap
      - run: npm run build --if-present
      - run: npm test
        env:
          DATOCMS_ACCOUNT_EMAIL: ${{ secrets.DATOCMS_ACCOUNT_EMAIL }}
          DATOCMS_ACCOUNT_PASSWORD: ${{ secrets.DATOCMS_ACCOUNT_PASSWORD }}
          DATOCMS_ORGANIZATION_ID: ${{ secrets.DATOCMS_ORGANIZATION_ID }}
